refresh_rate: 30 seconds
appenders:
    stdout:
        kind: console
        encoder:
            pattern: "{d(%Y-%m-%dT%H:%M:%S%z)} - [{l}] [{M}] - {h({m})} {n}"
    shift-manager:
        kind: console
        encoder:
            pattern: "{d(%Y-%m-%dT%H:%M:%S%z)} - [{l}] [{M}] [{f} - {L}] - {h({m})}{n}"
root:
    level: trace
    appenders:
        - stdout
loggers:
    shift_manager:
        level: trace
        appenders:
            - shift-manager
        additive: false
