
[development]
template_dir = "shift-manager-web/templates/"
static_dir = "shift-manager-web/static/"
jwt_key = "pluto"
jwt_exp = 900

[development.databases]
db = { url = "postgres://postgres:postgres@localhost:5432/shift-manager" }